/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DvBorderBox12: typeof import('@kjgl77/datav-vue3')['BorderBox12']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YoungCountUp: typeof import('./../src/components/YoungCountUp.vue')['default']
    YoungECharts: typeof import('./../src/components/YoungECharts/index.vue')['default']
    YoungHeader: typeof import('./../src/components/YoungHeader.vue')['default']
    YoungSectionContainer: typeof import('./../src/components/YoungSectionContainer.vue')['default']
    YoungSectionHeader: typeof import('./../src/components/YoungSectionHeader.vue')['default']
  }
}
